# window rules
windowrule = opacity 0.95 override, title:(.*)
windowrulev2 = opacity 1.0, fullscreen:1

# Visual Studio
windowrule = opacity 0.75 override, title:(Visual Studio Code)$

# Kitty
windowrule = opacity 0.75 override, class:(kitty)

# Scrcpy
windowrule = prop keepaspectratio, class:(scrcpy)
windowrule = opacity 1, class:(scrcpy)

# Steam
windowrule = float, class:(Steam)
windowrule = prop fullscreen 1, class:(steam_app_)(.*)
windowrule = opacity 1, class:(steam_app_)(.*)
windowrule = prop fullscreen 1, class:(steam_app_)(.*)
windowrule = opacity 0, initialTitle:(DropShadowWindow)
windowrule = noblur, initialTitle:(DropShadowWindow)
windowrule = nofocus, initialTitle:(DropShadowWindow)

# Rofi
windowrule = stayfocused, class:(rofi)

# Polkit
windowrule = float, class:(lxqt-policykit)

# Clipse
windowrule = center, class:(clipse)
windowrule = float, class:(clipse)
windowrule = size 960 560 override, class:(clipse)
windowrule = opacity 0.70 override, class:(clipse)

# QEMU 
windowrule = float, title:^(.*)(QEMU/KVM)$
#windowrule = size 1200 800 override, title:^(.*)(QEMU/KVM)$
windowrule = prop keepaspectratio, title:^(.*)(QEMU/KVM)$
windowrule = opacity 1, title:^(.*)(QEMU/KVM)$

# Picture in picture 
windowrule = float, title:^(Picture-in-Picture)$
windowrule = prop keepaspectratio, title:^(Picture-in-Picture)$
windowrule = opacity 1, title:^(Picture-in-Picture)$

# YouTube
windowrule = opacity 1, title:^(.*)( - YouTube)(.*)$

# VLC
windowrule = opacity 1, class:^(vlc)$

# tschuss
windowrule= float, class:(tschuss)
windowrule= move 0.5% 5%, class:(tschuss)
# windowrule= stayfocused, class:(tschuss)

# VIM
windowrule= opacity 0.90 override, title:(^vim.*)

# Ollama Hypr
windowrule = float, class:(hypr-ollama)
windowrule = center, class:(hypr-ollama)
windowrule = size 960 560 override, class:(hypr-ollama)
windowrule = opacity 0.70 override, class:(hypr-ollama)


# Blackout
windowrule = center, class:(blackout)
windowrule = float, class:(blackout)
windowrule = size 960 560 override, class:(blackout)
