source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
monitor=, 1920x1080@74.97,auto,auto, vrr, 1

general {
    gaps_in = 2.5
    gaps_out = 5
    border_size = 1
    col.active_border = $color4
    col.inactive_border = $color8

    layout = dwindle
}

cursor {
    inactive_timeout = 2
}


decoration {
    rounding = 5
    fullscreen_opacity = 1
    layerrule = blur,waybar
    layerrule = blur,rofi
    
    layerrule = blur, swaync-control-center
    layerrule = ignorezero, swaync-control-center
    layerrule = blur, swaync-notification-window
    layerrule = ignorezero, swaync-notification-window
#    layerrule = ignorealpha 0.65, swaync-control-center
 
    blur {
        enabled = true
        size = 4
        passes = 3
	ignore_opacity = true
	xray = false
	new_optimizations = true
    }
}

animations {
    enabled = yes

    bezier = myBezier, 0.05, 0.9, 0.1, 1.1
    bezier = myEase-in-out, 0.94, .01, 0, 0.97

    animation = windows, 1, 7, myEase-in-out
    animation = windowsOut, 1, 7, myEase-in-out
    animation = windowsMove, 1, 5, myEase-in-out
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, myEase-in-out
    animation = workspaces, 1, 6, myEase-in-out
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

gestures {
    workspace_swipe = on
}

input {
    kb_layout = us,br
    kb_options =  grp:alt_space_toggle
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
